### ISSUE TITLE
Revit - other versions?

### ISSUE THREAD

**Issue by aajameschung** [pix3lot/Slackit#15]
Really great tool, thanks for putting this together.

We have been experiencing issues with the addin not loading properly on machines that do not have Revit 2015 installed. 

![slackit error](https://user-images.githubusercontent.com/30355499/28532293-69f75eac-7067-11e7-9950-8c650c03d88e.png)

If a machine has Revit 2015 + any other version installed (including 2018), it works fine if we copy/paste the dll/addin files to the Addin folder for different versions. But if a computer doesn't have 2015 installed, the error comes up. Once we install Revit 2015, it works again.

The simple fix is just to install Revit 2015, but we may be "losing" that version soon due to our licensing set-up. So wondering if there's something else we need to install to future-proof. Any help would be greatly appreciated.

**Comment by djsiroky** [comment]
Hi @aajameschung,

Can you click the "Show details" down arrow on the dialog you included and show us what it says there?

Also, did you install SlackIt using the files from the SlackItRevit.zip file? I can't be sure, but the files in the zip file may be for Revit 2015 only, and therefore is looking for Revit 2015's API files. If Revit 2015 isn't installed, it can't find them and gives you the error you see above. 

We do have the ability to build different versions of Revit (2015-2017, but 2018 shouldn't be difficult to add) that reference the proper version's API files, so I think it's a matter of adding different zip files for each version.

**Comment by aajameschung** [comment]
Thanks for the quick response. Here's the requested details:

![slackit error expanded](https://user-images.githubusercontent.com/30355499/28542428-1649f26a-708a-11e7-93b8-3b0dc5b5c10a.png)

And yes, we installed it from the Revit zip file. It mentioned 2015 specifically, but when we found it worked, we moved those files into the other version add-in folders and found it worked too. However, we had all versions installed. Then on some project teams, those teams only had their project-specific version installed, which is when we realized the error occurred.

**Comment by pix3lot** [comment]
The issue is as @djsiroky mentioned, the files in the original zip were compiled to reference the Revit 2015 API and so without it the plugin failed. 

I added four zips to the repository for versions 2015, 2016, 2017, and 2018 and updated the Readme. Download the one you need and give it a go.

**Comment by aajameschung** [comment]
Great, really appreciate it.

Thanks again for all your efforts on this, very helpful tool.
