### ISSUE TITLE
Token Error

### ISSUE THREAD

**Issue by GabrielMartino** [pix3lot/Slackit#20]
Hi,

I am getting this error. I've issued multiple new tokens but it still doesn't work.

![image](https://user-images.githubusercontent.com/11638701/42484386-29085d7c-8436-11e8-82ec-73fd30c4b93b.png)

**Comment by pix3lot** [comment]
I have seen that issue come up when there are two channels that have the same name on your Slack site. It errors when gathering all the channels in this part of the code:
```
foreach (var item in ch.channels)
{ 
ch_name_id.Add(item.name, item.id); 
}
```
Can you check if you have duplicate channel names on your Slack site?

**Comment by GabrielMartino** [comment]
Thanks for the reply. We are in very different time zones (GMT+10
Australia).

I am currently using 2016 (will be moving to 2019 later this year). I made
a new Slack workspace so there aren't any channels with the same name.

I created the token with the Legacy Token Generator. That was as far as I
managed to get.

The addon seems to have installed properly as I is showing in Revit.

I really appreciate your help.

Kind Regards,
Gabriel Martino

**Comment by GabrielMartino** [comment]
This is what the basic test is showing me:

{
    "ok": true,
    "url": "https:\/\/8pencils.slack.com\/",
    "team": "8 Pencils",
    "user": "gabriel",
    "team_id": "TBNR22AVC",
    "user_id": "UBMF2G675"
}

**Comment by pix3lot** [comment]
Without a clearer error or knowing where it is failing it is hard to know exactly what is going wrong since it works for us just as it is uploaded here. I would guess that you are are entering the token correctly in the field, so I am a bit at a loss as where to look. 

Can you debug the code and step through and see on which line it is failing?

**Comment by GabrielMartino** [comment]
I have no idea where to start. What file should I be debugging?

**Comment by GabrielMartino** [comment]
Ok so all I have done to actually 'install' this addin was put these files
in the revit addins 2016 folder.

**Comment by GabrielMartino** [comment]
I put the .dll's in their debug folders but this came up.

**Comment by GabrielMartino** [comment]
Ok I got it to work. :) thank you for making the addin!

**Comment by pix3lot** [comment]
Great - glad you got it to work!
