### ISSUE TITLE
Consider using extensible storage instead of Shared Parameters to store custom data

### ISSUE THREAD

**Issue by djsiroky** [pix3lot/Slackit#3]
As I'm reading up on the topic of Extensible Storage in the Revit API, it seems like the perfect opportunity to house file-specific information without having to serialize anything or worry about the same shared parameter file being copied, then having multiple files using the same token. 

I'm going to look into this a bit myself, but I thought I'd post it here as well.

**Comment by pix3lot** [comment]
That would be great! I am not a big fan of saving the settings in a shared parameter. Its important for the settings to be embedded in the model so the Slack settings can be set once per project and saved to the file. 

I don't have much experience with Extensible Storage, but I remember looking into it and thought that the data had to be assigned to an Element within the project, which didn't sound like what we would want to do.

**Comment by djsiroky** [comment]
I thought the same thing, but [Jeremy Tammik's post ](http://thebuildingcoder.typepad.com/blog/2016/04/named-guid-storage-for-project-identification.html) about a project GUID actually prompted me to mention it

**Comment by djsiroky** [comment]
My most recent commit seems to have this working, but I'd like to do some more testing...Here it is: djsiroky/Slackit@43c9b2660f2c8619252f71e9a52dec6d1f368f72

The Element it's assigned to is a DataStorage object which is made for storing data from the API. I've tested syncing between two separate locals and the settings carry over and are updated on open, after sync, and when you launch the settings window (this covers using Reload Latest when the settings in the DataStorage from the central are different but there isn't an event to otherwise trigger re-checking that data for changes)

**Comment by pix3lot** [comment]
Thanks! Added #4 . I did also notice an issue that Extensible Storage as we have i produces and error when updating the code to have additional settings, if that project file that already had settings in the first place; but that's a different issue.

**Comment by djsiroky** [comment]
So that can be resolved on the code side by generating a new GUID in [ExtensibleStorage.cs](https://github.com/pix3lot/Slackit/blob/master/SlackitRevit/ExtensibleStorage.cs) when the Schema changes (saved settings are added or removed).

**Comment by pix3lot** [comment]
Nice, that's what I was thinking. Glad you confirmed it!
