### ISSUE TITLE
Screenshot function fails if C:\Temp does not exist

### ISSUE THREAD

**Issue by djsiroky** [pix3lot/Slackit#5]
Had a user experience this error when trying to use the screenshot button. It was resolved by creating a C:\Temp folder, but is there a better temp location that can be used ?

![image001](https://cloud.githubusercontent.com/assets/11220250/15622746/afdb82b4-2431-11e6-9062-3a389ff720ed.png)

**Comment by djsiroky** [comment]
https://msdn.microsoft.com/en-us/library/system.io.path.gettemppath(v=vs.110).aspx

This should put it in a location that will work. I can implement this over the weekend.

**Comment by pix3lot** [comment]
Great, much better,
