### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by RotoArk** [pix3lot/Slackit#8]
Hi Ben, I am Hailong. I contacted you on twitter. Thank you for getting back to me. Currently I am working at Roto Architects in LA. I am an Architect, I don't know too much about programming. Last week I went to a BIM conference in USC. During the conference, one of the speakers mentioned SlackIt. I think it will be a great tool for our office. Because we just started to use Revit, and we had a lot of problems with team member communication. Also we are using Slack in the office already as a project management tool. 

I downloaded the zip package from Gibhub. I followed the "read me" instruction to copy paste files. But when I open Revit, it says something like "can't find Slackit Revit.dll file". Did I miss something to download? 

Thank you so much.

**Comment by pix3lot** [comment]
It looks like the original Debug files weren't being included. So you likely were not getting the right files. I added a zip file to the Repo that has just the files you need. 

Unblock the zip, then extract the files to:
C:\ProgramData\Autodesk\Revit\Addins\2015
[SlackItRevit.zip](https://github.com/pix3lot/Slackit/blob/master/SlackItRevit.zip)

Let me know if that works.

**Comment by RotoArk** [comment]
Thank you. But it still doesn't work. Below is the warning information.  
![slackit screenshot](https://cloud.githubusercontent.com/assets/20732036/17385170/ca6ac0ec-5995-11e6-9d03-307a8b1c7f92.jpg)

**Comment by pix3lot** [comment]
The reference to a DLL isn't correct, or reading.

What version of Revit are you installing it to? The Zip, as is, only works with Revit 2015 and not Revit Architecture, or a discipline specific version of Revit.

And definitely make sure to unblock the Zip before extracting.

**Comment by RotoArk** [comment]
Ha, it works! I think the problem is I didn't unblock the zip file. Thank you so much!

**Comment by pix3lot** [comment]
Glad we got it worked out!
