### ISSUE TITLE
2016 & 2017 Versions

### ISSUE THREAD

**Issue by djsiroky** [pix3lot/Slackit#9]
I wanted to explore how to develop for Revit 2015, 2016, and 2017 simultaneously. Between 2015 and 2016 it's only changing the references to RevitAPI.dll and RevitAPIUI.dll and references to the assembly and images in `SlackRibbon.cs`. When you hit 2017, `TransactionMode.Automatic` becomes deprecated and has to be change. Additionally, the build should target .NET 4.5.2 instead of 4.5 because that' what the Revit references are built in.

Two options I see: 
1.  Create 2015, 2016, and 2017 branches on this repo. Each is essentially the same, except those items listed above. Any new changes are created on a separate branch, which can then be merged into all of the branches.
2. Using variables in the Visual Studio project to reference different assemblies and change file paths based on builds for 2015, 2016, 2017. See [this The Building Coder article](http://thebuildingcoder.typepad.com/blog/2013/11/multi-version-visual-studio-revit-add-in-wizard.html)

**Comment by pix3lot** [comment]
I was looking into Option 2 earlier and if we can get that working fairly easily that seems to be the better   option. It seems cleaner and it makes it possible to use for discipline specific versions, like Revit Architecture, which has a different path to the references.

**Comment by djsiroky** [comment]
[This video](https://www.youtube.com/watch?v=JrrVZjy5pBE) was really clear about making these changes. I've created build configurations for 2015, 2016, and 2017. It handles the Revit.API and RevitAPI.dll references, as well as the references to images in `SlackRibbon.cs`.  

As for the `TransactionMode.Automatic`, the only 2 occurrences of that code was where no changes were being made to the Revit document (in `SlackRibbon.cs` and `EventsApplication.cs`) and therefore it was either unnecessary or could be changed to `TransactionMode.Manual`

Finally, changing the target .NET build did not cause issues with the 2015 version. I need to do further testing with the 2016 and 2017 versions before making a PR, but this should be done by the end of the week.

**Comment by pix3lot** [comment]
I meant to say that this issue is fixed with # #10
